apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: jwenz723/demohttp-backend
      context: ./cmd/backend/
    - image: jwenz723/demohttp-frontend
      context: ./cmd/frontend/
  local:
  # You can enable this if you want skaffold to push built images into your docker registry. You will need to modify the image
  # path specified above to change `jwenz723` to your docker hub username.
#    push: true
deploy:
  kubectl:
    manifests:
      - ./k8s/*
portForward:
  - resourceType: deployment
    resourceName: skaffolddemo-frontend
    port: 8080
    localPort: 9000
  - resourceType: deployment
    resourceName: skaffolddemo-backend
    port: 8080
    localPort: 9001
