apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: jwenz723/demohttp-backend
      context: ./cmd/backend/
    - image: jwenz723/demohttp-frontend
      context: ./cmd/frontend/
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - ./k8s/*
portForward:
  - resourceType: deployment
    resourceName: skaffolddemo-frontend
    port: 8080
    localPort: 9000
