apiVersion: v1
kind: Service
metadata:
  name: skaffolddemo-frontend
  labels:
    app: skaffolddemo-frontend
spec:
  ports:
    - port: 8080
      name: skaffolddemo-frontend
  selector:
    app: skaffolddemo-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffolddemo-frontend
  labels:
    app: skaffolddemo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffolddemo-frontend
  template:
    metadata:
      labels:
        app: skaffolddemo-frontend
    spec:
      containers:
        - name: skaffolddemo-frontend
          image: jwenz723/demohttp-frontend
          args:
            - "-addr=:8080"
            - "-backend-addr=http://skaffolddemo-backend:8080"
          ports:
            - containerPort: 8080
