apiVersion: v1
kind: Service
metadata:
  name: skaffolddemo-backend
  labels:
    app: skaffolddemo-backend
spec:
  ports:
    - port: 8080
      name: skaffolddemo-backend
  selector:
    app: skaffolddemo-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffolddemo-backend
  labels:
    app: skaffolddemo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skaffolddemo-backend
  template:
    metadata:
      labels:
        app: skaffolddemo-backend
    spec:
      containers:
        - name: skaffolddemo-backend
          image: jwenz723/demohttp-backend
          args:
            - "-addr=:8080"
          ports:
            - containerPort: 8080
